heat_template_version: 2013-05-23
description: A load-balancer server
parameters:
  flavor:
    type: string
    description: flavor used by the servers
    default: my_flavor_xxx
  image:
    type: string
    description: Image used for servers
    default: image_xxxxx
  key_name:
    type: string
    description: SSH key to connect to the servers
    default: ssh_key_xxxx
  private_net_id:
    type: string
    default: net_id_xxxxx
  pool_id:
    type: string
    description: Pool to contact
    default: 11111
  scheduler_hints:
    type: string
    default: '[">=","$mem", "10", ">=","$ncpus", "1"]'
  chef_server_url:
    type: string
    default: http://127.0.0.1
  nameserver:
    type: string
    default: myserver
  db2_server_name:
    type: string
    default: db2_server

resources:
  wlp_server:
    type: IBMInc::EGO::Activity
    properties:
      containers:
        - description: "web server"
          name: web-server
          cpu: 1
          memory: 256
          image: dockerfile/nginx
          ports:
            - container_port: 9080
          volume_mounts:
            - name: www-data
              mount_path: /srv/www
          env:
            - name: DB2SERVERNAME
              value: { get_param: db2_server_name }
            - name: nameserver
              value: { get_param: nameserver }
            - name: chef_server_url
              value: { get_param: chef_server_url }
        - description: 'git monitor'
          name: git-monitor
          image: kubernetes/git-monitor
          memory: 200
          cpu: 2
          volume_mounts:
            - name: www-data
              mount_path: /data
      volumes:
        - name: string
          source: EmptyDir
          path: /
      network_id: {get_param: private_net_id}
      scheduler_hints: {get_param: scheduler_hints}


